### ISSUE TITLE
import inside functions

### ISSUE THREAD

**Issue by wingedRuslan** [WhitakerLab/scona#117]
Hi!

There are a bunch of functions, where **import statements** are inside the functions' body.
Is this made intentionally? Should I refactor and include import only at the top of a module??

Some references:
1) [PEP8](https://www.python.org/dev/peps/pep-0008/#imports)
> Imports are always put at the top of the file, just after any module comments and docstrings, and before module globals and constants.
2) [StackOverFlow Answer](https://stackoverflow.com/questions/128478/should-import-statements-always-be-at-the-top-of-a-module)

Module importing is quite fast, but not instant. This means that:
- Putting the imports at the top of the module is fine, because it's a trivial cost that's only paid once.
- Putting the imports within a function will cause calls to that function to take longer.

**Comment by Islast** [comment]
Yes you should always refactor the imports to be at the top of the module

**Comment by Islast** [comment]
self assigning so that I remember to add this to the development guide

**Comment by wingedRuslan** [comment]
@Islast What are you planning to add to the guide?

**Comment by Islast** [comment]
A note that in general imports should go at the top of the file

**Comment by KirstieJane** [comment]
(This is almost certainly me having no idea what I was doing when I wrote this code! Thank you for doing a much cleaner job @wingedRuslan & @Islast 💖)

**Comment by Islast** [comment]
Closing since #120 adds this style reccomendation to the documentation
