### ISSUE TITLE
Plot Network Measures

### ISSUE THREAD

**Issue by wingedRuslan** [WhitakerLab/scona#118]
Hi!

I would like to make a nice `plot_network_function`. So here is the 1st draft of the plot. Please give me feedback, what you like, what you don't like :smiley: 

The figure produced by Kirstie some time ago: (the screenshot taken from issue #1)
![image](https://user-images.githubusercontent.com/14000852/59020061-e22f7400-8851-11e9-81aa-2618b048188f.png)

My figures saved as files:

The numbers are arbitrary, the idea is that the function makes a bar plot of 2 dictionaries

- **Attempt 1** 
![attempt1](https://user-images.githubusercontent.com/14000852/59020396-95986880-8852-11e9-87ca-8a6d7f531310.png)

- **Attempt 2**
Just applied seaborn styles, the ones Kirstie did in the source code.
```
sns.set_style('white')
sns.set_context("poster", font_scale=2)
```

![attempt2](https://user-images.githubusercontent.com/14000852/59020434-ab0d9280-8852-11e9-9c5b-2869af8f5a1e.png)

What are the general recommendations I should follow concerning the ~beauty of~ plots?

Please write down also the preferences regarding the `plot_network_figures` how it should look like :)

**Comment by Islast** [comment]
These look great to me @wingedRuslan :sparkles:! I'm going to ping @KirstieJane as I know she has a more sophisticated eye for figures than I do!

**Comment by wingedRuslan** [comment]
@Islast Thanks for the feedback! By the end of this day, I will have all 3 planned functions implemented `plot_network_figures`, `plot_rich_club`, `plot_degree_dist`. And I will open an issue for created illustrations. Then it would be easier and more convenient for @KirstieJane to review all together, I guess.

**Comment by Islast** [comment]
discussion moved to #121
