### ISSUE TITLE
Feedback on created visualisations

### ISSUE THREAD

**Issue by wingedRuslan** [WhitakerLab/scona#119]
Hi all!

I've implemented visualisation tools for the following purposes:

1) `plot_rich_club` - for plotting the rich club values per degree along with the random rich club values created from a random network with a preserved degree distribution.

**Result**
![Rich_club_values](https://user-images.githubusercontent.com/14000852/59333881-e8b26580-8d01-11e9-91ba-bf120f397e18.png)

2) `plot_network_measures` - plotting network measures values along with the random network values values created from a random network

**Result**
![Barrr](https://user-images.githubusercontent.com/14000852/59333940-0f709c00-8d02-11e9-86f4-db56a40c2aaf.png)

3) `plot_degree_dist` - plotting the degree distribution along with the degree distribution of an Erdos Renyi random graph

**Result**
![3333Plot](https://user-images.githubusercontent.com/14000852/59333996-329b4b80-8d02-11e9-8e87-a705c6f86adb.png)

Kirstie's code was really helpful but mostly I've designed these functions by myself, so there are might be some features(changes) you would like to have and on the contrary not to have.

**Comment by Islast** [comment]
Is the code to produce these in your fork @wingedRuslan ?

**Comment by Islast** [comment]
I think we can safely move this discussion to pr #121
