### ISSUE TITLE
Choose a package name

### ISSUE THREAD

**Issue by Islast** [WhitakerLab/scona#19]
Update:
Please help us choose a package name by voting and suggesting in this [poll](https://poll.ly/#/Gx4yMMY7) :tada: :sparkles: :cherry_blossom: 
You can find a little background information on what we're doing and why we need to choose a new name in our [blog](https://whitakerlab.github.io/blog/Boaty-McBrainNetworksInPython/)

-----------------------------------------------------------------------------------------------------
A naming convention for python packages and modules is reccomended in [PEP 8](https://www.python.org/dev/peps/pep-0008/#package-and-module-names) 
> Modules should have short, all-lowercase names. Underscores can be used in the module name if it improves readability. Python packages should also have short, all-lowercase names, although the use of underscores is discouraged.

What do you think gang? Should we stick to our guns and go `BrainNetworksInPython`, compromise on `brainnetworksinpython`, `bnip`, `pythonbrainnetworks`, `brainnetworks`, `networkbrains`, or abandon propriety and go `networknoggins`

**Comment by KirstieJane** [comment]
Deeeeeeecisions!! 😬😬😬

I’d love to tweet this but we need a little more information about the project to go with the question.

Would you be up for writing a mini blog post (5-10 sentences!) to explain what we’re aiming for and why we need a name? I don’t know if there’s an easy way to embed a poll in Jekyll but that might be fun! Very simple google form maybe? 

Also, have you done any googling for these names? Or brain networks in python packages that already exist? We need to make sure they don’t overlap.

I will say that we should *definitely* conform to the guidelines - no need to go rogue on the camel case etc.

**Comment by Islast** [comment]
Great. Yes I will write up a blog post and check what's already been taken

**Comment by KirstieJane** [comment]
Could also include `py` in the various names rather than `python`? So `pybrainnets` maybe?

(Soooo many options!)

**Comment by Islast** [comment]
Suggested this morning by a friend: turnip (=**tur**ing **n**etworks **i**n **p**ython). No reference to brains unfortunately, but what a cute idea!

**Comment by Islast** [comment]
Note to self: [poll.ly](https://poll.ly/#/) is a good tool for polls to which voters can add suggestions

**Comment by Islast** [comment]
The blog post is now up https://whitakerlab.github.io/blog/Boaty-McBrainNetworksInPython/

**Comment by Islast** [comment]
We have finally firmly settled on the new name `scona` :tada: :cookie:
