### ISSUE TITLE
update view_corr_mat in visualisation commands

### ISSUE THREAD

**Issue by Islast** [WhitakerLab/scona#83]
The function `view_corr_mat` in [`visualisation_commands`](https://github.com/WhitakerLab/scona/blob/master/scona/scripts/visualisation_commands.py) needs to be redesigned to plot matrices that are not saved as files.

**Comment by wingedRuslan** [comment]
Is this issue still relevant?

Right now `view_corr_mat` takes **filename** as an argument. Then corr_mat is loaded(numpy.loadtxt) from the file. 
Would you like the function to take **the corr_mat object** as an argument instead of filename?

**Comment by Islast** [comment]
Ideally I would like the function to be such that one can pass a correlation matrix (say a numpy array or pandas dataframe) and plot that, or optionally pass a filename instead.

**Comment by Islast** [comment]
adressed in #108
