### ISSUE TITLE
Fix typo in readme & code of conduct file

### ISSUE THREAD

**Issue by KirstieJane** [WhitakerLab/scona#90]
I’ve seen this typo while browsing `scona`:cookie: on my phone and I figured I’d leave it here in case someone wanted a super easy first contribution 😸 

Here are screen grabs of the typo. (One was copied from the other which is why they’re the same!) A pull request to get rid of that stray “an” would be greatly appreciated ✨ 
![08e8c1fb-bb09-4ec4-8909-4829ff4eba05](https://user-images.githubusercontent.com/3626306/51805009-eb835100-225f-11e9-9ad3-de6c384fa566.jpeg)
![46d5e61c-6f72-40b1-b4ec-b479a31d51a5](https://user-images.githubusercontent.com/3626306/51805010-ec1be780-225f-11e9-986e-bde38d90a3f3.jpeg)

![Uploading 14F6A615-3FFF-4CB0-B20B-45F100B7B2F5.jpeg…]()

**Comment by lokesh541** [comment]
Hi fixed it. thanks
